### ISSUE TITLE
Test Failing for Mozilla/5.0 (Mobile; rv:26.0) Gecko/18.0 Firefox/26.0

### ISSUE THREAD

**Issue by sumitbinnani** [ua-parser/uap-java#15]
> Expected: is <{"family": "Firefox OS", "major": "1", "minor": "0", "patch": "1", "patch_minor": ""}>
     got: <{"family": "Firefox OS", "major": "1", "minor": "0", "patch": "", "patch_minor": ""}>

**Comment by nsonntag** [comment]
There is a pull request ready to fix this.

**Comment by Ironholds** [comment]
Yup; fixed with #11 . Thanks!
