### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by sebastinakash** [ua-parser/uap-java#21]
What went wrong:
Could not resolve all dependencies for configuration ':crmweb:compile'.
> Could not find group:uap-clj, module:uap-clj, version:1.3.1.
 Required by:
     com.myntra:crmweb:1.0

compile "uap-clj:uap-clj:1.3.1"

**Comment by bpossolo** [comment]
Hi @sebastinakash 
I'm not sure what you were trying to do here but here is the correct GAV to use if importing as a maven dependency:
```
<dependency>
  <groupId>com.github.ua-parser</groupId>
  <artifactId>uap-java</artifactId>
  <version>1.5.0</version>
</dependency>
```
