### ISSUE TITLE
Git clone needs --recursive flag for mvn package to work.

### ISSUE THREAD

**Issue by robertboxall** [ua-parser/uap-java#33]
Wasted about 10 minutes this morning trying to clone this and found that mvn package command failed - debugged and realized you need the regex file from the uap-core project. Then after a little digging came across a recent change to project has a git submodule in it. 

It seems for this to work you need the clone to add --recursive 

git clone --recursive https://github.com/ua-parser/uap-java.git

At least on a macbook with latest git and mvn via homebrew - maybe add this to readme?

**Comment by robertboxall** [comment]
Or after normal clone run this command.

git submodule update --init --recursive

**Comment by bpossolo** [comment]
Updated the README with your suggestion.
thank you
https://github.com/ua-parser/uap-java#build
