### ISSUE TITLE
Parser constructor shouldn't throw IOException

### ISSUE THREAD

**Issue by Maia-Everett** [ua-parser/uap-java#40]
`IOException` is a checked exception, which forces all code using `new Parser` to catch an "impossible" `IOException`. A checked exception should be thrown in the case of a logically possible failure caused by external circumstances — for example, file system or network errors. Since `uap-java` reads its rules from a file on the classpath, and the syntax of the file is under the developer's control, any exception when reading this file indicates a programming error, which should be represented as an unchecked exception.

The constructor should catch the `IOException` and wrap it in an `AssertionError` (or maybe `RuntimeException`).

**Comment by bpossolo** [comment]
@Maia-Everett this has been addressed by [this commit](https://github.com/ua-parser/uap-java/commit/074a05901cf8b3e7230c7664eae8567f6e32b6a0).

The latest build has been pushed to Maven central so you can consume the new version by upgrading to 1.5.0
