### ISSUE TITLE
[Question] Is the Parser class thread safe?

### ISSUE THREAD

**Issue by gayashanbc** [ua-parser/uap-java#44]
Can someone tell me whether the `Parser` class is thread-safe?
If I'm using the Parser class in multiple places, what is the best we to do it?

**Comment by bpossolo** [comment]
It should be safe yes.
I've been using it in a thread-safe manner for a while.
There is this [outstanding issue](https://github.com/ua-parser/uap-java/issues/41) which needs to be addressed though.

Just create the Parser instance on app startup then pass the reference around.
You can have multiple threads invoking the `parser.parse()` method
or if you're using a dependency injection framework, you can bind an instance of the Parser in Singleton scope

**Comment by anttibrax** [comment]
I have read the code with this in mind and could not find anything that wasn't thread safe from the Parser class. It uses java.util.regex.Pattern, which is thread safe and does not expose the Matchers outside of method scope.

**Comment by bpossolo** [comment]
Gonna close this issue since it’s been resolved. Thanks @anttibrax
