### ISSUE TITLE
Building jar doesn't work

### ISSUE THREAD

**Issue by horeapopa** [ua-parser/uap-java#53]
By following the instructions from the Readme the jar can't be built.

The uap-core is not a jar and there is no dependency that can be fetched.

uap-core is a submodule that contains metadata and it should be packed with the actual uap-java jar package.

Commit https://github.com/ua-parser/uap-java/commit/36e306267175ff656fef50d70b29f2cc5ea4dd9c introduced this issue, left a comment there also.

Please amend the documentation or the build to have it working.

**Comment by bpossolo** [comment]
fixed
