### ISSUE TITLE
Please release to include latest changes to UAP-Core

### ISSUE THREAD

**Issue by brindy** [ua-parser/uap-java#63]
Hello,

I recently made some changes to UAP-Core to support DuckDuckGo's mobile browsers and was wondering if I could trouble you to perform a release, please?

Thanks in advance.

**Comment by brindy** [comment]
Hi @bpossolo - sorry to bug you about this but lack of support for DuckDuckGo is causing some problems for us and we know that some sites in particular make use of this library. 

Any ETA on when the next release will be?

Thanks!

**Comment by bpossolo** [comment]
yes. will do it this weekend

**Comment by bpossolo** [comment]
@brindy 
i just built/deployed a new version 1.5.1
it's been pushed to sonatype but hasn't mirrored to maven central just yet.
you'll see it appear here once it's been mirrored:
https://mvnrepository.com/artifact/com.github.ua-parser/uap-java

**Comment by brindy** [comment]
Thank you so much!

**Comment by bpossolo** [comment]
my pleasure!
