### ISSUE TITLE
IOException not imported by CacheParser

### ISSUE THREAD

**Issue by milimetric** [ua-parser/uap-java#65]
I must be missing something obvious because for me the latest doesn't build with `cannot find symbol IOException`.  I looked at the blame and the use was added 2 years ago and the imports haven't changed in 8 years:

https://github.com/ua-parser/uap-java/blame/master/src/main/java/ua_parser/CachingParser.java#L45

Where's my blind spot here?

**Comment by bpossolo** [comment]
ah it broke due to [this PR](https://github.com/ua-parser/uap-java/commit/7484bb6b08b28625b8929c8480044191e225027c#diff-835e1c7aa4030f5fc46848cd23229690d7c9549aca64c13c6d2631470b53d309) which I just merged.
sorry about that. will fix shortly

**Comment by bpossolo** [comment]
I just fixed and pushed to master

**Comment by bpossolo** [comment]
the blame dates are a little odd. the PR was crafted 2 years ago but it was only merged a couple days ago. I would expect it to show the date that the change was applied to the master branch but alas it shows the date that the original commit was made..

**Comment by bpossolo** [comment]
fyi: latest version of uap-java is published 1.5.2
it should show up in maven central repo soon
