### ISSUE TITLE
Update uap-core to 0.13.0

### ISSUE THREAD

**Issue by rquetin-androme** [ua-parser/uap-java#66]
As far as I know, the current 1.5.2 release of uap-java uses uap-core 0.12.0, which lags behind on the current version of uap-core (0.13.0).

Notable changes since uap-core 0.12.0 include improved support for iOS 13 user agents and initial support for iOS 14 user agents.

**Comment by bpossolo** [comment]
I just build and released uap-jap 1.5.3 which includes uap-core 0.15.0
