### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by zhuqingchao** [ua-parser/uap-java#69]
ua = 
```
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44"
```

parse result 
```json
{"user_agent": {"family": "Edge", "major": "95", "minor": "0", "patch": "1020"}, "os": {"family": "Linux", "major": "", "minor": "", "patch": "", "patch_minor": ""}, "device": {"family": "Other"}}
```
Is the ua parsed rightly?  the os major and os minor is null. and the device is other.

My browser is edge, os is ubuntu 18.x.

**Comment by bpossolo** [comment]
That seems plausible. The user agent string simply says `Linux x86_64` so there isn’t much the parser can glean from it.

**Comment by zhuqingchao** [comment]
tks,  got it.
